name: "Hello World workflow"

# Controls when the action will run. Triggers the workflow on push sone to "master" or production branch
on:
  push:
    branches:
      - Main
      - production

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: "Print Hello World"
        run: echo "Hello World from GitHub Actions"
      
      - name: "Print Current Directory"
        run: pwd
      
      - name: "Print date"
        run: date
