name: "Multi event Pipeline / Workflow"

on:
    push: #Event
        branches:
            - Main
            - test
    pull_request: #Event
        branches:
            - Main
            - test
    workflow_dispatch: 

jobs:
    on-push: #job name
        if: github.event_name == 'push' 
        runs-on: ubuntu-latest
        steps:
            - name: "Running on main branch" #step 1
              run: echo "Running on main branch"
    on-pull-request: #job name
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on pull request" #step 1
              run: echo "Running on pull request"

    on-pull-request-closed:
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on pull request closed" #step 1
              run: echo "Running on pull request closed"


              
    on-workflow-dispatch: #job 3
        if: github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        steps: 
            - name: "Running on workflow dispatch" #step 1
              run: echo "Running on workflow dispatch"

